In [56]:
from pathlib import Path

import polars as pl

ROOT = Path.cwd()
OUT_DIR = ROOT / "data" / "output"
if not OUT_DIR.exists():
    OUT_DIR = ROOT.parent / "data" / "output"

parquet_path = OUT_DIR / "dashboard" / "metrics.parquet"
if not parquet_path.exists():
    raise FileNotFoundError(f"Parquet file not found: {parquet_path}")

raw_df = pl.read_parquet(parquet_path)

In [57]:
raw_df.head()

shape: (5, 11)
┌───────────────────────┬──────────┬────────┬──────────┬───┬─────────┬───────┬────────┬────────────┐
│ unique_id             ┆ wmape    ┆ sum_y  ┆ n_points ┆ … ┆ seccion ┆ store ┆ sku    ┆ node_kind  │
│ ---                   ┆ ---      ┆ ---    ┆ ---      ┆   ┆ ---     ┆ ---   ┆ ---    ┆ ---        │
│ str                   ┆ f64      ┆ f64    ┆ u32      ┆   ┆ str     ┆ str   ┆ str    ┆ str        │
╞═══════════════════════╪══════════╪════════╪══════════╪═══╪═════════╪═══════╪════════╪════════════╡
│ 23||T:00095||S:578305 ┆ 0.747188 ┆ 345.0  ┆ 624      ┆ … ┆ 23      ┆ 00095 ┆ 578305 ┆ tienda_sku │
│ 1||S:411891           ┆ 1.0      ┆ 5.0    ┆ 0        ┆ … ┆ 1       ┆ null  ┆ 411891 ┆ sku        │
│ 23||S:455458          ┆ 0.755938 ┆ 232.4  ┆ 0        ┆ … ┆ 23      ┆ null  ┆ 455458 ┆ sku        │
│ 1||T:00154||S:455436  ┆ 0.6875   ┆ 16.0   ┆ 731      ┆ … ┆ 1       ┆ 00154 ┆ 455436 ┆ tienda_sku │
│ 1||T:00001||S:400744  ┆ 0.935549 ┆ 1950.0 ┆ 731      ┆ … ┆ 1       ┆ 00001 ┆ 400744 ┆ tienda_sku │
└───────────────────────┴──────────┴────────┴──────────┴───┴─────────┴───────┴────────┴────────────┘

In [58]:
best_sku = {
    sec: {
        sto: (
            raw_df.filter(
                (pl.col("node_kind") == "tienda_sku")
                & (pl.col("seccion") == sec)
                & (pl.col("store") == sto)
                & (pl.col("unidad") == "Valor ($)")
                & pl.col("wmape").is_not_null()
                & (pl.col("wmape") != 0)
            )
            .sort("wmape")
            .get_column("sku")
            .head(50)
            .to_list()
        )
        for sto in (
            raw_df.filter(
                (pl.col("node_kind") == "tienda")
                & (pl.col("seccion") == sec)
                & (pl.col("unidad") == "Valor ($)")
            )
            .sort("wmape")
            .get_column("store")
            .head(5)
            .to_list()
        )
    }
    for sec in ["1", "23"]
}

best_sku

{'1': {'00001': ['39472',
   '580661',
   '459977',
   '516028',
   '46499',
   '541427',
   '41796',
   '75048',
   '46853',
   '567332',
   '483046',
   '208',
   '64048',
   '447684',
   '478352',
   '43549',
   '2322',
   '190454',
   '42231',
   '58905',
   '218557',
   '127359',
   '565118',
   '46713',
   '379145',
   '6656',
   '61722',
   '478353',
   '447627',
   '299478',
   '406342',
   '406018',
   '605956',
   '1063',
   '118209',
   '152629',
   '133336',
   '145082',
   '127360',
   '39591',
   '43550',
   '1760',
   '31894',
   '541426',
   '41542',
   '570746',
   '38333',
   '55921',
   '57488',
   '500770'],
  '00003': ['581783',
   '106356',
   '58905',
   '39472',
   '85860',
   '143871',
   '168765',
   '473932',
   '116741',
   '64048',
   '46499',
   '127359',
   '124382',
   '31894',
   '169938',
   '332817',
   '495934',
   '492075',
   '478352',
   '101740',
   '494947',
   '495933',
   '477265',
   '101743',
   '51782',
   '565871',
   '145082',
   '6656',
   '108193',
   '565117',
   '127360',
   '817',
   '40399',
   '555434',
   '494254',
   '568161',
   '384028',
   '89405',
   '483046',
   '456854',
   '379145',
   '106662',
   '364448',
   '568160',
   '46853',
   '38072',
   '316080',
   '555432',
   '580661',
   '522734'],
  '00211': ['568161',
   '489263',
   '606556',
   '568160',
   '565871',
   '456855',
   '100622',
   '495933',
   '495934',
   '127359',
   '456854',
   '555432',
   '525569',
   '533462',
   '603372',
   '235135',
   '555435',
   '521184',
   '485256',
   '488509',
   '492255',
   '85860',
   '163',
   '31894',
   '20516',
   '128667',
   '574784',
   '385982',
   '565117',
   '485254',
   '590083',
   '378685',
   '127360',
   '29042',
   '457287',
   '473159',
   '457195',
   '458283',
   '43422',
   '477265',
   '394500',
   '595787',
   '817',
   '229229',
   '501033',
   '584835',
   '406341',
   '390634',
   '2138',
   '402936'],
  '00154': ['495933',
   '568160',
   '521184',
   '456855',
   '163',
   '489263',
   '538209',
   '85860',
   '100622',
   '505356',
   '457195',
   '127360',
   '55899',
   '495934',
   '565871',
   '456854',
   '485254',
   '390615',
   '332817',
   '394501',
   '606556',
   '604526',
   '39593',
   '407940',
   '128667',
   '236659',
   '43422',
   '159124',
   '2503',
   '507612',
   '485341',
   '26839',
   '525569',
   '492255',
   '2466',
   '574784',
   '595790',
   '510510',
   '555434',
   '565120',
   '457193',
   '459431',
   '14587',
   '234395',
   '127359',
   '600262',
   '494949',
   '507034',
   '488509',
   '390633'],
  '00063': ['412091',
   '278120',
   '568160',
   '43422',
   '29042',
   '565871',
   '407312',
   '456855',
   '495934',
   '394501',
   '127360',
   '606556',
   '489263',
   '568161',
   '127359',
   '163',
   '485255',
   '578306',
   '574784',
   '555434',
   '145082',
   '209052',
   '31894',
   '485256',
   '101743',
   '488509',
   '109551',
   '507034',
   '394500',
   '495933',
   '390615',
   '565117',
   '32934',
   '555432',
   '817',
   '453870',
   '156703',
   '394499',
   '46853',
   '584104',
   '604516',
   '453991',
   '20840',
   '332817',
   '159124',
   '51782',
   '521184',
   '555435',
   '525569',
   '404531']},
 '23': {'00006': ['603595',
   '587387',
   '514081',
   '333113',
   '218058',
   '45642',
   '333110',
   '593461',
   '5898',
   '582946',
   '385301',
   '519600',
   '448849',
   '17245',
   '126196',
   '25879',
   '523647',
   '288718',
   '90052',
   '306918',
   '197305',
   '448848',
   '590253',
   '365658',
   '462965',
   '421274',
   '190',
   '582947',
   '126192',
   '333112',
   '45643',
   '474665',
   '402588',
   '221258',
   '10887',
   '360938',
   '543148',
   '8119',
   '523646',
   '30316',
   '383387',
   '17437',
   '61735',
   '335462',
   '555595',
   '526486',
   '534518',
   '10796',
   '501541',
   '21759'],
  '00012': ['113618',
   '582947',
   '71765',
   '197305',
   '306915',
   '218058',
   '598287',
   '45642',
   '419464',
   '466270',
   '78005',
   '565854',
   '474665',
   '385301',
   '368517',
   '546020',
   '365658',
   '555679',
   '451148',
   '526486',
   '333112',
   '126196',
   '320256',
   '28303',
   '354150',
   '430969',
   '25879',
   '99775',
   '523646',
   '532695',
   '600291',
   '430574',
   '598285',
   '5574',
   '454131',
   '501664',
   '532696',
   '32757',
   '22867',
   '65576',
   '582341',
   '17665',
   '451163',
   '582946',
   '477895',
   '90052',
   '556935',
   '512241',
   '383387',
   '306918'],
  '00005': ['113618',
   '448634',
   '32757',
   '197305',
   '474665',
   '28303',
   '392615',
   '566325',
   '211797',
   '63009',
   '90052',
   '221258',
   '45642',
   '385301',
   '165',
   '320256',
   '71770',
   '136718',
   '126196',
   '451337',
   '501237',
   '306915',
   '135286',
   '17665',
   '571469',
   '25879',
   '218058',
   '365658',
   '520377',
   '68909',
   '474664',
   '450298',
   '22867',
   '526486',
   '419840',
   '582341',
   '546020',
   '563221',
   '71765',
   '466270',
   '419464',
   '582949',
   '466271',
   '543149',
   '582946',
   '330287',
   '582947',
   '451163',
   '532696',
   '392613'],
  '00046': ['195295',
   '219991',
   '113618',
   '501237',
   '103986',
   '306915',
   '600005',
   '126192',
   '453094',
   '455106',
   '306918',
   '28303',
   '532695',
   '565854',
   '455105',
   '398514',
   '430969',
   '514454',
   '71765',
   '392615',
   '10887',
   '493601',
   '75952',
   '99039',
   '5574',
   '295341',
   '455525',
   '17437',
   '351576',
   '32746',
   '515003',
   '546019',
   '5898',
   '431267',
   '451337',
   '458174',
   '86911',
   '333113',
   '455112',
   '501238',
   '185',
   '306916',
   '457706',
   '190',
   '455463',
   '21759',
   '110364',
   '221258',
   '454935',
   '451148'],
  '00095': ['71765',
   '113618',
   '532695',
   '455106',
   '546020',
   '126192',
   '306918',
   '430969',
   '103986',
   '466270',
   '21759',
   '190',
   '306915',
   '99775',
   '197305',
   '451163',
   '543148',
   '532696',
   '96729',
   '221258',
   '17680',
   '295341',
   '28303',
   '457706',
   '579041',
   '451338',
   '32746',
   '165',
   '65576',
   '333112',
   '63861',
   '518211',
   '218058',
   '421274',
   '400125',
   '563221',
   '451337',
   '92248',
   '306917',
   '398514',
   '392615',
   '593460',
   '543149',
   '90052',
   '457059',
   '32661',
   '453094',
   '518457',
   '126196',
   '136718']}}

In [59]:
best_skus = {}
for sec in ["1", "23"]:
    best_skus.update(best_sku[sec])
best_skus

{'00001': ['39472',
  '580661',
  '459977',
  '516028',
  '46499',
  '541427',
  '41796',
  '75048',
  '46853',
  '567332',
  '483046',
  '208',
  '64048',
  '447684',
  '478352',
  '43549',
  '2322',
  '190454',
  '42231',
  '58905',
  '218557',
  '127359',
  '565118',
  '46713',
  '379145',
  '6656',
  '61722',
  '478353',
  '447627',
  '299478',
  '406342',
  '406018',
  '605956',
  '1063',
  '118209',
  '152629',
  '133336',
  '145082',
  '127360',
  '39591',
  '43550',
  '1760',
  '31894',
  '541426',
  '41542',
  '570746',
  '38333',
  '55921',
  '57488',
  '500770'],
 '00003': ['581783',
  '106356',
  '58905',
  '39472',
  '85860',
  '143871',
  '168765',
  '473932',
  '116741',
  '64048',
  '46499',
  '127359',
  '124382',
  '31894',
  '169938',
  '332817',
  '495934',
  '492075',
  '478352',
  '101740',
  '494947',
  '495933',
  '477265',
  '101743',
  '51782',
  '565871',
  '145082',
  '6656',
  '108193',
  '565117',
  '127360',
  '817',
  '40399',
  '555434',
  '494254',
  '568161',
  '384028',
  '89405',
  '483046',
  '456854',
  '379145',
  '106662',
  '364448',
  '568160',
  '46853',
  '38072',
  '316080',
  '555432',
  '580661',
  '522734'],
 '00211': ['568161',
  '489263',
  '606556',
  '568160',
  '565871',
  '456855',
  '100622',
  '495933',
  '495934',
  '127359',
  '456854',
  '555432',
  '525569',
  '533462',
  '603372',
  '235135',
  '555435',
  '521184',
  '485256',
  '488509',
  '492255',
  '85860',
  '163',
  '31894',
  '20516',
  '128667',
  '574784',
  '385982',
  '565117',
  '485254',
  '590083',
  '378685',
  '127360',
  '29042',
  '457287',
  '473159',
  '457195',
  '458283',
  '43422',
  '477265',
  '394500',
  '595787',
  '817',
  '229229',
  '501033',
  '584835',
  '406341',
  '390634',
  '2138',
  '402936'],
 '00154': ['495933',
  '568160',
  '521184',
  '456855',
  '163',
  '489263',
  '538209',
  '85860',
  '100622',
  '505356',
  '457195',
  '127360',
  '55899',
  '495934',
  '565871',
  '456854',
  '485254',
  '390615',
  '332817',
  '394501',
  '606556',
  '604526',
  '39593',
  '407940',
  '128667',
  '236659',
  '43422',
  '159124',
  '2503',
  '507612',
  '485341',
  '26839',
  '525569',
  '492255',
  '2466',
  '574784',
  '595790',
  '510510',
  '555434',
  '565120',
  '457193',
  '459431',
  '14587',
  '234395',
  '127359',
  '600262',
  '494949',
  '507034',
  '488509',
  '390633'],
 '00063': ['412091',
  '278120',
  '568160',
  '43422',
  '29042',
  '565871',
  '407312',
  '456855',
  '495934',
  '394501',
  '127360',
  '606556',
  '489263',
  '568161',
  '127359',
  '163',
  '485255',
  '578306',
  '574784',
  '555434',
  '145082',
  '209052',
  '31894',
  '485256',
  '101743',
  '488509',
  '109551',
  '507034',
  '394500',
  '495933',
  '390615',
  '565117',
  '32934',
  '555432',
  '817',
  '453870',
  '156703',
  '394499',
  '46853',
  '584104',
  '604516',
  '453991',
  '20840',
  '332817',
  '159124',
  '51782',
  '521184',
  '555435',
  '525569',
  '404531'],
 '00006': ['603595',
  '587387',
  '514081',
  '333113',
  '218058',
  '45642',
  '333110',
  '593461',
  '5898',
  '582946',
  '385301',
  '519600',
  '448849',
  '17245',
  '126196',
  '25879',
  '523647',
  '288718',
  '90052',
  '306918',
  '197305',
  '448848',
  '590253',
  '365658',
  '462965',
  '421274',
  '190',
  '582947',
  '126192',
  '333112',
  '45643',
  '474665',
  '402588',
  '221258',
  '10887',
  '360938',
  '543148',
  '8119',
  '523646',
  '30316',
  '383387',
  '17437',
  '61735',
  '335462',
  '555595',
  '526486',
  '534518',
  '10796',
  '501541',
  '21759'],
 '00012': ['113618',
  '582947',
  '71765',
  '197305',
  '306915',
  '218058',
  '598287',
  '45642',
  '419464',
  '466270',
  '78005',
  '565854',
  '474665',
  '385301',
  '368517',
  '546020',
  '365658',
  '555679',
  '451148',
  '526486',
  '333112',
  '126196',
  '320256',
  '28303',
  '354150',
  '430969',
  '25879',
  '99775',
  '523646',
  '532695',
  '600291',
  '430574',
  '598285',
  '5574',
  '454131',
  '501664',
  '532696',
  '32757',
  '22867',
  '65576',
  '582341',
  '17665',
  '451163',
  '582946',
  '477895',
  '90052',
  '556935',
  '512241',
  '383387',
  '306918'],
 '00005': ['113618',
  '448634',
  '32757',
  '197305',
  '474665',
  '28303',
  '392615',
  '566325',
  '211797',
  '63009',
  '90052',
  '221258',
  '45642',
  '385301',
  '165',
  '320256',
  '71770',
  '136718',
  '126196',
  '451337',
  '501237',
  '306915',
  '135286',
  '17665',
  '571469',
  '25879',
  '218058',
  '365658',
  '520377',
  '68909',
  '474664',
  '450298',
  '22867',
  '526486',
  '419840',
  '582341',
  '546020',
  '563221',
  '71765',
  '466270',
  '419464',
  '582949',
  '466271',
  '543149',
  '582946',
  '330287',
  '582947',
  '451163',
  '532696',
  '392613'],
 '00046': ['195295',
  '219991',
  '113618',
  '501237',
  '103986',
  '306915',
  '600005',
  '126192',
  '453094',
  '455106',
  '306918',
  '28303',
  '532695',
  '565854',
  '455105',
  '398514',
  '430969',
  '514454',
  '71765',
  '392615',
  '10887',
  '493601',
  '75952',
  '99039',
  '5574',
  '295341',
  '455525',
  '17437',
  '351576',
  '32746',
  '515003',
  '546019',
  '5898',
  '431267',
  '451337',
  '458174',
  '86911',
  '333113',
  '455112',
  '501238',
  '185',
  '306916',
  '457706',
  '190',
  '455463',
  '21759',
  '110364',
  '221258',
  '454935',
  '451148'],
 '00095': ['71765',
  '113618',
  '532695',
  '455106',
  '546020',
  '126192',
  '306918',
  '430969',
  '103986',
  '466270',
  '21759',
  '190',
  '306915',
  '99775',
  '197305',
  '451163',
  '543148',
  '532696',
  '96729',
  '221258',
  '17680',
  '295341',
  '28303',
  '457706',
  '579041',
  '451338',
  '32746',
  '165',
  '65576',
  '333112',
  '63861',
  '518211',
  '218058',
  '421274',
  '400125',
  '563221',
  '451337',
  '92248',
  '306917',
  '398514',
  '392615',
  '593460',
  '543149',
  '90052',
  '457059',
  '32661',
  '453094',
  '518457',
  '126196',
  '136718']}

In [60]:
sales_path = OUT_DIR / "sales.parquet"
sales_df = pl.read_parquet(sales_path)
sales_df["STORE_ID", "SKU_ID"].unique()

shape: (39_834, 2)
┌──────────┬────────┐
│ STORE_ID ┆ SKU_ID │
│ ---      ┆ ---    │
│ str      ┆ str    │
╞══════════╪════════╡
│ 00022    ┆ 365958 │
│ 00001    ┆ 545601 │
│ 00012    ┆ 559417 │
│ 00122    ┆ 109612 │
│ 00001    ┆ 228983 │
│ …        ┆ …      │
│ 00001    ┆ 514031 │
│ 00003    ┆ 424641 │
│ 00063    ┆ 463161 │
│ 00025    ┆ 396549 │
│ 00006    ┆ 50     │
└──────────┴────────┘

In [61]:
best_skus_df = pl.DataFrame(
    [
        {"STORE_ID": sto, "SKU_ID": sku}
        for sto, skus in best_skus.items()
        for sku in skus
    ]
).cast(
    {
        "STORE_ID": pl.String,
        "SKU_ID": pl.String,
    }
)

sales_df.join(
    best_skus_df,
    on=["STORE_ID", "SKU_ID"],
    how="inner",
)

shape: (300_847, 8)
┌─────────────────────┬────────┬──────────┬───────────┬─────────┬─────────┬──────────┬──────────┐
│ SALES_DATE          ┆ SKU_ID ┆ STORE_ID ┆ TRAN_TYPE ┆ SLS_VAL ┆ SLS_QTY ┆ RTRN_QTY ┆ RTRN_VAL │
│ ---                 ┆ ---    ┆ ---      ┆ ---       ┆ ---     ┆ ---     ┆ ---      ┆ ---      │
│ datetime[μs]        ┆ str    ┆ str      ┆ str       ┆ f64     ┆ f64     ┆ f64      ┆ f64      │
╞═════════════════════╪════════╪══════════╪═══════════╪═════════╪═════════╪══════════╪══════════╡
│ 2025-11-26 00:00:00 ┆ 221258 ┆ 00006    ┆ P         ┆ 3442.66 ┆ 48.0    ┆ 0.0      ┆ 0.0      │
│ 2025-05-05 00:00:00 ┆ 568161 ┆ 00003    ┆ R         ┆ 1014.43 ┆ 8.0     ┆ 0.0      ┆ 0.0      │
│ 2026-04-29 00:00:00 ┆ 229229 ┆ 00211    ┆ R         ┆ 64.0    ┆ 1.0     ┆ 0.0      ┆ 0.0      │
│ 2024-10-04 00:00:00 ┆ 555432 ┆ 00003    ┆ R         ┆ 346.5   ┆ 8.0     ┆ 0.0      ┆ 0.0      │
│ 2024-12-09 00:00:00 ┆ 532696 ┆ 00095    ┆ R         ┆ 342.0   ┆ 6.0     ┆ 0.0      ┆ 0.0      │
│ …                   ┆ …      ┆ …        ┆ …         ┆ …       ┆ …       ┆ …        ┆ …        │
│ 2026-04-30 00:00:00 ┆ 568161 ┆ 00211    ┆ P         ┆ 693.0   ┆ 7.0     ┆ 0.0      ┆ 0.0      │
│ 2025-04-22 00:00:00 ┆ 218058 ┆ 00095    ┆ P         ┆ 953.0   ┆ 7.0     ┆ 0.0      ┆ 0.0      │
│ 2025-02-12 00:00:00 ┆ 30316  ┆ 00006    ┆ R         ┆ 1008.23 ┆ 16.0    ┆ 0.0      ┆ 0.0      │
│ 2024-10-01 00:00:00 ┆ 5574   ┆ 00012    ┆ R         ┆ 254.37  ┆ 6.0     ┆ 0.0      ┆ 0.0      │
│ 2024-05-22 00:00:00 ┆ 817    ┆ 00211    ┆ R         ┆ 202.0   ┆ 2.0     ┆ 0.0      ┆ 0.0      │
└─────────────────────┴────────┴──────────┴───────────┴─────────┴─────────┴──────────┴──────────┘

In [62]:
best_sku = {}

sec = "1"

stos = (
    raw_df.filter(
        (pl.col("node_kind") == "tienda")
        & (pl.col("seccion") == sec)
        & (pl.col("unidad") == "Valor ($)")
    )
    .sort("wmape")
    .get_column("store")
    .head(5)
    .to_list()
)

skus = (
    raw_df.filter(
        (pl.col("node_kind") == "tienda_sku")
        & (pl.col("seccion") == sec)
        & (pl.col("unidad") == "Valor ($)")
        & pl.col("store").is_in(stos)
        & pl.col("wmape").is_not_null()
        & (pl.col("wmape") != 0)
        & (pl.col("n_points") == 28)
    )
    .group_by("sku")
    .agg(
        pl.col("store").n_unique().alias("n_stores"),
        pl.col("wmape").mean().alias("wmape_mean"),
    )
    .filter(pl.col("n_stores") == len(stos))
    .sort("wmape_mean")
    .head(50)
    .get_column("sku")
    .to_list()
)

skus

[]

In [63]:
selected_stores = {
    sec: (
        raw_df.filter(
            (pl.col("node_kind") == "tienda")
            & (pl.col("seccion") == sec)
            & (pl.col("unidad") == "Valor ($)")
            & pl.col("wmape").is_not_null()
            & (pl.col("wmape") != 0)
        )
        .sort("wmape")
        .get_column("store")
        .head(5)
        .to_list()
    )
    for sec in ["1", "23"]
}
selected_stores

{'1': ['00001', '00003', '00211', '00154', '00063'],
 '23': ['00006', '00012', '00005', '00046', '00095']}

In [64]:
best_sku = []

for sec, stores in selected_stores.items():
    sku_candidates = (
        raw_df.filter(
            (pl.col("node_kind") == "tienda_sku")
            & (pl.col("seccion") == sec)
            & (pl.col("unidad") == "Valor ($)")
            & pl.col("store").is_in(stores)
            & pl.col("wmape").is_not_null()
            & (pl.col("wmape") != 0)
            & (pl.col("n_points") >= 20)
        )
        .sort("wmape")
        .head(50)
        .get_column("sku")
        .to_list()
    )

    best_sku += sku_candidates

best_sku

['412091',
 '278120',
 '39472',
 '581783',
 '580661',
 '106356',
 '459977',
 '495933',
 '516028',
 '568160',
 '46499',
 '541427',
 '41796',
 '75048',
 '58905',
 '46853',
 '567332',
 '39472',
 '85860',
 '568161',
 '483046',
 '208',
 '143871',
 '489263',
 '606556',
 '64048',
 '447684',
 '568160',
 '478352',
 '43549',
 '565871',
 '2322',
 '168765',
 '190454',
 '473932',
 '42231',
 '58905',
 '456855',
 '218557',
 '568160',
 '43422',
 '127359',
 '116741',
 '100622',
 '565118',
 '46713',
 '379145',
 '6656',
 '495933',
 '61722',
 '603595',
 '195295',
 '219991',
 '587387',
 '113618',
 '514081',
 '582947',
 '333113',
 '113618',
 '501237',
 '113618',
 '218058',
 '103986',
 '71765',
 '448634',
 '113618',
 '32757',
 '45642',
 '71765',
 '197305',
 '474665',
 '28303',
 '333110',
 '197305',
 '306915',
 '593461',
 '306915',
 '218058',
 '5898',
 '392615',
 '598287',
 '600005',
 '582946',
 '45642',
 '385301',
 '519600',
 '448849',
 '17245',
 '126196',
 '25879',
 '419464',
 '523647',
 '288718',
 '466270',
 '90052',
 '306918',
 '197305',
 '566325',
 '448848',
 '590253']

In [65]:
parquet_path = OUT_DIR / "forecast.parquet"
if not parquet_path.exists():
    raise FileNotFoundError(f"Parquet file not found: {parquet_path}")

raw_df = pl.read_parquet(parquet_path)

In [66]:
raw_df

shape: (27_131_620, 23)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ unique_id  ┆ ds        ┆ value    ┆ valuehat ┆ … ┆ valuehat_ ┆ yhat_tien ┆ valuehat_ ┆ modelo_se │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ seccion   ┆ da        ┆ tienda    ┆ leccionad │
│ str        ┆ date      ┆ f64      ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ o         │
│            ┆           ┆          ┆          ┆   ┆ f32       ┆ f32       ┆ f32       ┆ ---       │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1          ┆ 2024-05-2 ┆ 2.1347e6 ┆ 2.0427e6 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 6         ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 1          ┆ 2024-05-2 ┆ 1.9304e6 ┆ 2.0117e6 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 7         ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 1          ┆ 2024-05-2 ┆ 2.0906e6 ┆ 2.2787e6 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 8         ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 1          ┆ 2024-05-2 ┆ 1.8514e6 ┆ 1.9099e6 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 9         ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 1          ┆ 2024-05-3 ┆ 1.7116e6 ┆ 1.8177e6 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 0         ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 23||T:0020 ┆ 2026-01-2 ┆ 0.0      ┆ 0.0      ┆ … ┆ 2.082007e ┆ 1.0       ┆ 63203.121 ┆ tienda    │
│ 0||S:99008 ┆ 8         ┆          ┆          ┆   ┆ 6         ┆           ┆ 094       ┆           │
│ 23||T:0020 ┆ 2026-01-2 ┆ 0.0      ┆ 0.0      ┆ … ┆ 2416458.5 ┆ 1.0       ┆ 70014.789 ┆ tienda    │
│ 0||S:99008 ┆ 9         ┆          ┆          ┆   ┆           ┆           ┆ 062       ┆           │
│ 23||T:0020 ┆ 2026-01-3 ┆ 0.0      ┆ 0.0      ┆ … ┆ 3.2618e6  ┆ 1.0       ┆ 93981.406 ┆ tienda    │
│ 0||S:99008 ┆ 0         ┆          ┆          ┆   ┆           ┆           ┆ 25        ┆           │
│ 23||T:0020 ┆ 2026-01-3 ┆ 0.0      ┆ 0.31     ┆ … ┆ 4.1157e6  ┆ 2.0       ┆ 126997.34 ┆ tienda    │
│ 0||S:99008 ┆ 1         ┆          ┆          ┆   ┆           ┆           ┆ 375       ┆           │
│ 23||T:0020 ┆ 2026-02-0 ┆ 0.0      ┆ 0.0      ┆ … ┆ 2.7766e6  ┆ 1.0       ┆ 85268.398 ┆ tienda    │
│ 0||S:99008 ┆ 1         ┆          ┆          ┆   ┆           ┆           ┆ 438       ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘